#!/usr/bin/env python3
"""Regenerate or check ``price_tracker.core._generated_currency_symbols``.

``--write [PATH]`` recomputes the table from the Babel installed here and
rewrites the module at ``PATH`` (default: the real, versioned module).
``--check [PATH]`` compares the mapping in the module at ``PATH`` (default:
the real one) against a fresh computation, and exits 1 if they differ — the
canary for a Babel upgrade that changes the currency-symbol data.

Before importing ``currency_symbols``, a fake ``_generated_currency_symbols``
module (``GENERATED_SYMBOLS = {}``) is inserted into ``sys.modules``, so the
regeneration never depends on the validity of the file it is about to
replace: a hand-corrupted or Babel-drifted generated module cannot block its
own repair.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import types
from pathlib import Path
from shutil import which

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PATH = REPO_ROOT / "src" / "price_tracker" / "core" / "_generated_currency_symbols.py"

_HEADER = "# generated by scripts/gen_currency_symbols.py, do not edit.\n"


def _fake_generated_module() -> None:
    fake = types.ModuleType("price_tracker.core._generated_currency_symbols")
    fake.GENERATED_SYMBOLS = {}  # type: ignore[attr-defined]
    sys.modules["price_tracker.core._generated_currency_symbols"] = fake


def _load_candidate(path: Path) -> dict[str, frozenset[str]]:
    """Import the ``GENERATED_SYMBOLS`` mapping at ``path``, whatever its module name."""
    import importlib.util

    spec = importlib.util.spec_from_file_location("_gen_currency_symbols_candidate", path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise RuntimeError(f"cannot load {path} as a Python module")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return dict(module.GENERATED_SYMBOLS)


def _render(table: dict[str, frozenset[str]]) -> str:
    lines = [_HEADER, '"""Data module: the Babel-generated part of the currency symbol table.\n']
    lines.append('Regenerate with ``scripts/gen_currency_symbols.py --write``.\n"""\n\n')
    lines.append("from __future__ import annotations\n\n")
    lines.append("GENERATED_SYMBOLS: dict[str, frozenset[str]] = {\n")
    for key in sorted(table):
        codes = ", ".join(f'"{code}"' for code in sorted(table[key]))
        lines.append(f'    "{key}": frozenset({{{codes}}}),\n')
    lines.append("}\n")
    return "".join(lines)


def _format(path: Path) -> None:
    ruff = which("ruff")
    if ruff is not None:
        subprocess.run([ruff, "format", str(path)], check=False, capture_output=True)


def _write(path: Path) -> int:
    _fake_generated_module()
    from price_tracker.core import currency_symbols

    table = currency_symbols.generate_symbols()
    path.write_text(_render(table), encoding="utf-8")
    _format(path)
    return 0


def _check(path: Path) -> int:
    _fake_generated_module()
    from price_tracker.core import currency_symbols

    fresh = currency_symbols.generate_symbols()
    candidate = _load_candidate(path)
    if candidate != fresh:
        print(
            "Babel changed: run scripts/gen_currency_symbols.py --write and review the diff",
            file=sys.stderr,
        )
        return 1
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", nargs="?", const="", metavar="PATH")
    group.add_argument("--check", nargs="?", const="", metavar="PATH")
    args = parser.parse_args(argv)

    if args.write is not None:
        path = Path(args.write) if args.write else DEFAULT_PATH
        return _write(path)
    path = Path(args.check) if args.check else DEFAULT_PATH
    return _check(path)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
