# generated by scripts/gen_currency_symbols.py, do not edit.
"""Data module: the Babel-generated part of the currency symbol table.
Regenerate with ``scripts/gen_currency_symbols.py --write``.
"""

from __future__ import annotations

GENERATED_SYMBOLS: dict[str, frozenset[str]] = {
    "$US": frozenset({"USD"}),
    "CA$": frozenset({"CAD"}),
    "CN¥": frozenset({"CNY"}),
    "GH₵": frozenset({"GHS"}),
    "MOP$": frozenset({"MOP"}),
    "NT$": frozenset({"TWD"}),
    "RD$": frozenset({"DOP"}),
    "T$": frozenset({"TOP"}),
    "WS$": frozenset({"WST"}),
    "֏": frozenset({"AMD"}),
    "؋": frozenset({"AFN"}),
    "৳": frozenset({"BDT"}),
    "៛": frozenset({"KHR"}),
    "₡": frozenset({"CRC"}),
    "₦": frozenset({"NGN"}),
    "₭": frozenset({"LAK"}),
    "₮": frozenset({"MNT"}),
    "₱": frozenset({"PHP"}),
    "₲": frozenset({"PYG"}),
    "₸": frozenset({"KZT"}),
    "₼": frozenset({"AZN"}),
    "₽": frozenset({"RUB"}),
    "₾": frozenset({"GEL"}),
}
